-- SQL statements to update package_type column
-- Run this in Supabase SQL Editor

UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פאי רועים אישי';
UPDATE menu_items SET package_type = 'אינגליש קייק' WHERE name = 'פאי רועים ';
UPDATE menu_items SET package_type = 'מארז חצי ליטר' WHERE name = 'בוייקוס גבינות';
UPDATE menu_items SET package_type = '700 גרם' WHERE name = 'פלטת אנטי פסטי';
UPDATE menu_items SET package_type = '400 גרם' WHERE name = 'חציל סטייק סלרי';
UPDATE menu_items SET package_type = '1 קילו' WHERE name = 'חמין';
UPDATE menu_items SET package_type = 'חצי קילו' WHERE name = 'חמין';
UPDATE menu_items SET package_type = '1 קילו' WHERE name = 'חמין ללא ביצה';
UPDATE menu_items SET package_type = 'חצי קילו' WHERE name = 'חמין ללא ביצה';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק ירקות';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק ירקות';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק עוף ';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק בטטה';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק בטטה';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק ירקות לקוסקוס';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק ירקות לקוסקוס';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק ירקות וגריסים';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק ירקות גריסים ';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק עגבניות';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק עגבניות';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק עדשים אדומות';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק עדשים אדומות';
UPDATE menu_items SET package_type = '1 ליטר' WHERE name = 'מרק עדשים ירוקות';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'מרק עדשים ירוקות';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת בטטה חלבי';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת ברוקלי חלבית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת פטריות חלבי';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פשטידת ירקות אישית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת ירקות פרווה גדול';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פשטידת כרובית אישית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת כרובית גדולה';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פשטידת קישואים אישית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת קישואים גדולה';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פשטידת תפוח אדמה אישית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת תפוח אדמה גדולה ';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'פשטידת תרד אישית';
UPDATE menu_items SET package_type = 'עגולה גדולה' WHERE name = 'פשטידת תרד גדולה';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'קיגל ירושלמי אישי';
UPDATE menu_items SET package_type = 'אינגליש קייק גדולה' WHERE name = 'קיגל ירושלמי גדול';
UPDATE menu_items SET package_type = 'פשטידה אישית' WHERE name = 'קיגל מתוק אישי';
UPDATE menu_items SET package_type = 'אינגליש קייק גדולה' WHERE name = 'קיגל מתוק גדול';
UPDATE menu_items SET package_type = 'אינגליש קייק בינוני' WHERE name = 'מאפה טחינה';
UPDATE menu_items SET package_type = 'חצי ליטר' WHERE name = 'סביח';
UPDATE menu_items SET package_type = 'רבע ליטר' WHERE name = 'סביח';
UPDATE menu_items SET package_type = 'ליטר' WHERE name = 'חציל סטייק סלרי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'איטלקי';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'איטלקי';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'בצל מטוגן';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גזר מרוקאי';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'גזר מרוקאי';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'וולדורף';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'זיתים ברוטב עגבניות';
UPDATE menu_items SET package_type = '1000 גרם' WHERE name = 'חומוס 1 ק"ג';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס חריף';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס טונסאי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס טחינה';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס טחינה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס ירושלמי ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס ירושלמי ';
UPDATE menu_items SET package_type = '400 גרם' WHERE name = 'חומוס מבושל';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס מבושל';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס מזרחי ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס מזרחי ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס מסבחה ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס מסבחה ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס מסעדות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חזרת ביתית';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חזרת ביתית';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס מסעדות';
UPDATE menu_items SET package_type = '330 גרם' WHERE name = 'חמוצים אסייתי';
UPDATE menu_items SET package_type = '360 גרם' WHERE name = 'חמוצים סיני';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס סופ"ש';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס סופ"ש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חומוס שמן זית וזעתר ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חומוס שמן זית וזעתר ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חילבה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל בטעם כבד';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל בטעם כבד';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל במיונז ';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'חציל במיונז';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל בשומשום';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל מרוקאי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל נורמנדי';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'חציל סטייק';
UPDATE menu_items SET package_type = '430 גרם' WHERE name = 'חציל סטייק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש בטחינה';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל על האש בטחינה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש בלקני';
UPDATE menu_items SET package_type = '320 גרם' WHERE name = 'חצילים כבושים';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל על האש בלקני';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש בלקני חריף';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש במיונז';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל על האש במיונז';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל דרוזי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל דרוזי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש ובצל ירוק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש טבעי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל על האש טבעי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש סיציליאני';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש צרפתי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'כרוב אדום במיונית';
UPDATE menu_items SET package_type = '460 גרם' WHERE name = 'כרוב אדום במיונית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל על האש רומני';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'חציל על האש רומני';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה פלפל צ’ומה';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'סלט כרוב אפונה  ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט כרוב אפונה  ';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'סלט כרוב גזר';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'רוטב לשקשוקה ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'רצועות חציל';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'רצועות חציל';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'שום כתוש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'תפוח אדמה כפרי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'תפוח אדמה כפרי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט כרוב גזר';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'סלט כרוב תירס';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט כרוב תירס';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'סלט כרוב פירות יבשים';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט כרוב פירות יבשים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל תאילנדי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חציל תאילנדי ברוטב צ''ילי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'חרוסת';
UPDATE menu_items SET package_type = '450 גרם' WHERE name = 'טבולה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פטריות שמיר 250 גרם';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'פטריות שמיר 500 גרם';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פטריות תירס 250 גרם';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'פטריות תירס 500 גרם';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלפל טוניסאי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלפל צ''ומה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלפלת בלימון';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פרוסות חציל בתחמיץ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'צ''ימיצ''ורי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'קינואה בעשבי תיבול';
UPDATE menu_items SET package_type = '380 גרם' WHERE name = 'קינואה בעשבי תיבול';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'קישוא בטעם כבד ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'קישוא בטעם כבד';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'קישוא סיני';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט משוויה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טורקי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טורקי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה  ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טחינה מסעדות ירוקה';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טחינה סופ"ש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה סופ"ש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה עמבה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'כרוב לבן במיונית';
UPDATE menu_items SET package_type = '460 גרם' WHERE name = 'כרוב לבן במיונית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'כרובית אמריקאית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'מטבוחה';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'מטבוחה';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'מיקס בריאות';
UPDATE menu_items SET package_type = '210 גרם' WHERE name = 'מיקס חריף';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טחינה ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה ירוקה';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טחינה ירוקה ';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טחינה מסעדות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה מסעדות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טחינה מסעדות ירוקה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט מאש';
UPDATE menu_items SET package_type = '450 גרם' WHERE name = 'סלט מאש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט מטבוחה חריפה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'שום על האש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'רגל קרושה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט בטטות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'רגל קרושה וביצה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלסה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלק  250 גרם ';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'סלק 500 גרם ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'עגבניות חריפות 250 גרם';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טבולה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'איקרה ';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'איקרה ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'איקרה לקס';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'דג במיונית';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'דג במיונית';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'הרינג בשמן';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'סלט הרינג עם בצל';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'הרינג כבוש';
UPDATE menu_items SET package_type = '350 גרם' WHERE name = 'הרינג כבוש 350 גרם';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'סלט מטיאס אמיתי במרינדה';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'סלט מטיאס אמיתי ובצל';
UPDATE menu_items SET package_type = '320 גרם' WHERE name = 'מטיאס קצוץ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'הרינג במיונית';
UPDATE menu_items SET package_type = '215 גרם' WHERE name = 'הרינג נורווגי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה במיונז';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טונה במיונז ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה ברוטב עגבניות';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טונה ברוטב עגבניות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה זיתים לימון כבוש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה מהבית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה פיקנטי';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'טונה פיקנטי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'מוס טונה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלמידה בשמן';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלמידה מקולפת ללא עצמות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה סלרי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה ספייסי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט דגים';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט דגים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלמונז';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלמון ממרח';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלמון אפוי על גחלים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טונה מעושנת במיונז';
UPDATE menu_items SET package_type = '420 גרם' WHERE name = 'בלינצ''ס אוכמניות וגבינה';
UPDATE menu_items SET package_type = '150 גרם' WHERE name = 'טריו שוקולד חלבי';
UPDATE menu_items SET package_type = '470 גרם' WHERE name = 'בלינצ''ס גבינה';
UPDATE menu_items SET package_type = '420 גרם' WHERE name = 'בלינצ''ס גבינה ודובדבנים';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'בלינצ''ס גבינה מופחת סוכר';
UPDATE menu_items SET package_type = '350 גרם' WHERE name = 'בלינצ''ס גבינה וצימוקים';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'אגסים ביין';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'בוואריה פרווה ';
UPDATE menu_items SET package_type = '165 גרם' WHERE name = 'מלבי שמנת';
UPDATE menu_items SET package_type = '440 גרם' WHERE name = 'בוואריה שוקולד משפחתית';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'בוואריה שוקולד חלבי';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'מוס אוראו';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'עוגת גבינה פירורים';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'מוס ריבת חלב';
UPDATE menu_items SET package_type = '110 גרם' WHERE name = 'מוס דואט פרווה ';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'מוס שוקולד פרווה';
UPDATE menu_items SET package_type = '170 גרם' WHERE name = 'מלבי פרווה';
UPDATE menu_items SET package_type = '110 גרם' WHERE name = 'מוס שוקולד חלבי';
UPDATE menu_items SET package_type = '140 גרם' WHERE name = 'קדאיף חלבי';
UPDATE menu_items SET package_type = '400 גרם' WHERE name = 'סלט פירות';
UPDATE menu_items SET package_type = '120 גרם' WHERE name = 'מוס גבינה ופירות יער';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'מוס שוקולד לבן';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'בוואריה שוקולד פרווה';
UPDATE menu_items SET package_type = '440 גרם' WHERE name = 'עוגת גבינה פירות יער';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'צימעס ';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'קומפוט של פעם';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'בוואריה חלבי ';
UPDATE menu_items SET package_type = '440 גרם' WHERE name = 'עוגת גבינה משפחתית';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'גזר ברוטב תפוזים';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'אבוקדו';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'אריסה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט ביצים';
UPDATE menu_items SET package_type = '480 גרם' WHERE name = 'סלט ביצים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט ביצים בצל ירוק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט ביצים ועירית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סלט ביצים ושמיר';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'בולגרית בצל ירוק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'בולגרית בצל ירוק מפולפלת ';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'בולגרית 5%';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'בולגרית עגבניות מיובשות ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'ממרח בולגרית פסטו ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'בולגרית פסטו עגבניות ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה טבעונית טבעית  ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה טבעונית עגבניוח ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה טבעונית פלפלים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה טבעונית פסטו';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה 5% בצל ירוק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'לאבנה זעתר ושמן זית 5%';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'לאבנה 5%';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינת פטה ופלפלים';
UPDATE menu_items SET package_type = '220 גרם' WHERE name = 'קוביות בולגרית בפסטו';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינת שמנת זיתים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פטה 21%';
UPDATE menu_items SET package_type = '150 גרם' WHERE name = 'פלפלונים ממולאים בפטה';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'צאזיקי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'לאבנה כדורים בשמן זית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'שמנת קלמטה';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'שמנת שום שמיר';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה 5% טבעית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה 5% שום שמיר';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינה 5% סלמון ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינת שמנת טבעית';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינת שמנת ירקות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'גבינת שמנת סלמון';
UPDATE menu_items SET package_type = '390 גרם' WHERE name = 'גזר לימון';
UPDATE menu_items SET package_type = '390 גרם' WHERE name = 'גזר לימון חריף';
UPDATE menu_items SET package_type = '350 גרם' WHERE name = 'גזר פיקנטי';
UPDATE menu_items SET package_type = '370 גרם' WHERE name = 'זית טסוס יבש';
UPDATE menu_items SET package_type = '270 גרם' WHERE name = 'זיתים ירוקים ללא חרצנים';
UPDATE menu_items SET package_type = '340 גרם' WHERE name = 'זית סורי מפולפל';
UPDATE menu_items SET package_type = '330 גרם' WHERE name = 'זית סורי שבור';
UPDATE menu_items SET package_type = '320 גרם' WHERE name = 'זית קלמטה';
UPDATE menu_items SET package_type = '320 גרם' WHERE name = 'זיתים ביין';
UPDATE menu_items SET package_type = '320 גרם' WHERE name = 'זיתים מנזנילו';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'טבעות פלפל חריף';
UPDATE menu_items SET package_type = '280 גרם' WHERE name = 'טבעות זיתים ירוקים';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'ירקות מעורבים';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב אדום כבוש';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב גזר בלימון';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב גזר ירוק';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב לבן כבוש ללא סוכר';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב סיני שומשום וחמניות';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'כרוב שמיר בלימון';
UPDATE menu_items SET package_type = '270 גרם' WHERE name = 'זית קלמטה מגולען';
UPDATE menu_items SET package_type = '330 גרם' WHERE name = 'לימון כבוש';
UPDATE menu_items SET package_type = '350 גרם' WHERE name = 'לימון כבוש חריף';
UPDATE menu_items SET package_type = '340 גרם' WHERE name = 'לפת';
UPDATE menu_items SET package_type = '340 גרם' WHERE name = 'מוסייר';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'פלפל אדום שלם';
UPDATE menu_items SET package_type = '230 גרם' WHERE name = 'פלפל רצועות';
UPDATE menu_items SET package_type = '500 גרם' WHERE name = 'סלט כרוב גזר';
UPDATE menu_items SET package_type = '400 גרם' WHERE name = 'זיתים בסגנון טהיטי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'פלפל חריף מקולף';
UPDATE menu_items SET package_type = '210 גרם' WHERE name = 'פלפל שיפקה';
UPDATE menu_items SET package_type = '400 גרם' WHERE name = 'מלפפון בייתי';
UPDATE menu_items SET package_type = '280 גרם' WHERE name = 'מלפפון במלח';
UPDATE menu_items SET package_type = '570 גרם' WHERE name = 'מלפפון  במלח בדלי';
UPDATE menu_items SET package_type = '280 גרם' WHERE name = 'מלפפון במלח ביתי פיקנטי';
UPDATE menu_items SET package_type = '570 גרם' WHERE name = 'מלפפון במלח ביתי פיקנטי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טפנד זיתים ירוקים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'טפנד זיתים שחורים';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'ממרח לימון';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'ממרח עגבניות מיובשות';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'ממרח פלפל אדום מיובש';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'ממרח פסטו בזיליקום';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סחוג אדום ';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'סחוג ירוק';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'עמבה';
UPDATE menu_items SET package_type = '300 גרם' WHERE name = 'גוואקמולי ';
UPDATE menu_items SET package_type = '100 גרם' WHERE name = 'סלמון מעושן 100 גרם';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'סלמון מעושן 200 גרם';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר חומוס';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר כוסמין';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר מרוקאי מתוק';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר עדשים';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר פשתן ';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר שיבולת שועל טבעי';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר שיבולת שועל פיקנטי';
UPDATE menu_items SET package_type = '200 גרם' WHERE name = 'קרקר שיבולת שועל שום בצל';
UPDATE menu_items SET package_type = '270 גרם' WHERE name = 'מגולגלות תמרים ואגוזים פרווה';
UPDATE menu_items SET package_type = '270 גרם' WHERE name = 'מגולגלות נוטלה חלבי';
UPDATE menu_items SET package_type = '250 גרם' WHERE name = 'עוגיות גרנולה';